version: '3.4'

services:
  squid:
    image: cooolin/socks5
    container_name: socks5
    ports:
      - "1080:1080"
    environment:
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=1080
      - PROXY_USER=user
      - PROXY_PASS=password
    restart: always
