version: '3'
services:
  v2ray:
    image: v2ray/official
    container_name: v2ray
    ports:
      - 22222:22222
    volumes:
      - ./config:/etc/v2ray
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

    restart: always
