version: '3'

services:

  mongo:
    image: mongo
    container_name: mongodb

    ports:
      - 27017:27017
    volumes:
      - /home/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: phish
      MONGO_INITDB_ROOT_PASSWORD: phish123098
    #   MONGO_INITDB_DATABASE: test
    restart: always

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: phish
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: phish123098
  #   restart: always