version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123098
      MYSQL_DATABASE: db
    network_mode: "bridge"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    # restart: always
